1.20a
git-svn-id: svn://tug.org/pdftex/branches/stable@11 7b5bf505-3498-49f7-8177-37ec8b90719f

diff --git a/source/src/texk/kpathsea/mktexpk b/source/src/texk/kpathsea/mktexpk
--- a/source/src/texk/kpathsea/mktexpk
+++ b/source/src/texk/kpathsea/mktexpk
@@ -7,7 +7,7 @@
 # te@dbs.uni-hannover.de, kb@mail.tug.org, and infovore@xs4all.nl.
 # Public domain.
 
-version='$Id: mktexpk,v 1.28 2002/11/11 09:45:40 olaf Exp $'
+version='$Id: mktexpk,v 1.31 2004/04/01 20:50:01 olaf Exp $'
 progname=`echo $0 | sed 's%.*/%%'`
 usage="Usage: $progname [OPTIONS] NAME [REDIRECT],
   Create a PK font.
@@ -119,6 +119,7 @@ if kpsewhich $NAME.mf >/dev/null 2>&1 || mktexmf $NAME >/dev/null 2>&1; then
      400) MODE=nexthi;;
      600) MODE=ljfour;;
     1270) MODE=linoone;;
+    8000) MODE=dpdfezzz;;
        *) echo "$progname: Can't guess mode for $BDPI dpi devices." >&2
           echo "$progname: Use a config file, or update me." >&2
           exit 1
@@ -139,7 +140,7 @@ else
     ps2pk)
       # grep for the font in $PSMAPFILE.  These are base font names, such as
       # rpplr (the original) or pplr0 (an interim step) or pplr8r (current).
-      : ${PSMAPFILE=`kpsewhich --format='dvips config' psfonts.map ps2pk.map`}
+      : ${PSMAPFILE=`kpsewhich --format=map psfonts.map ps2pk.map`}
       pattern="^$NAME"'([ 	]|$)' 
       psline=`egrep "$pattern" $PSMAPFILE | tail -1`
       if test -n "$psline"; then
@@ -213,16 +214,20 @@ fi
 
 echo "$progname: Running $cmd"
 $cmd </dev/null || {
-  # Don't abort if only "Strange path" or "bad pos" errors occurr.
+  # Don't abort if only "Strange path", "bad pos" or "angle(0,0)"
+  # errors occurr.
   grep '^!' $NAME.log | sort >$$.errs 2>/dev/null
   grep '^! Strange path' $$.errs >$$.strange 2>/dev/null
   grep '^! bad pos.' $$.errs >$$.badpos 2>/dev/null
-  cat $$.badpos $$.strange | sort > $$.errs_accept
+  grep '^! angle(0,0) is taken as zero.' $$.errs >$$.angle 2>/dev/null
+  cat $$.badpos $$.strange $$.angle | sort > $$.errs_accept
   if cmp $$.errs $$.errs_accept >/dev/null 2>&1; then
     test -s $$.strange >/dev/null 2>&1 \
       && echo "$progname: warning: \`$cmd' caused strange path errors." >&2
     test -s $$.badpos >/dev/null 2>&1 \
       && echo "$progname: warning: \`$cmd' caused bad pos errors." >&2
+    test -s $$.angle >/dev/null 2>&1 \
+      && echo "$progname: warning: \`$cmd' caused angle(0,0) errors." >&2
   else
     echo "$progname: \`$cmd' failed." >&2
     test -s $NAME.log && mv -f $NAME.log "$KPSE_DOT"
diff --git a/source/src/texk/kpathsea/mktextfm b/source/src/texk/kpathsea/mktextfm
--- a/source/src/texk/kpathsea/mktextfm
+++ b/source/src/texk/kpathsea/mktextfm
@@ -7,7 +7,7 @@
 # te@dbs.uni-hannover.de, kb@mail.tug.org, and infovore@xs4all.nl.
 # Public domain.
 
-version='$Id: mktextfm,v 1.26 2002/11/12 17:56:21 olaf Exp $'
+version='$Id: mktextfm,v 1.27 2004/07/03 19:25:15 olaf Exp $'
 progname=`echo $0 | sed 's%.*/%%'`
 usage="Usage: $progname [--destdir DESTDIR] FONT.
 
@@ -94,11 +94,20 @@ fi
 
 echo "$progname: Running $cmd"
 $cmd </dev/null || {
-  grep '^!' $NAME.log >$$.errs 2>/dev/null
+  # Don't abort if only "Strange path", "bad pos" or "angle(0,0)"
+  # errors occurr.
+  grep '^!' $NAME.log | sort >$$.errs 2>/dev/null
   grep '^! Strange path' $$.errs >$$.strange 2>/dev/null
-  if cmp $$.errs $$.strange >/dev/null 2>&1 \
-    && test -s $$.strange >/dev/null 2>&1; then
-    echo "$progname: warning: \`$cmd' caused strange path errors." >&2
+  grep '^! bad pos.' $$.errs >$$.badpos 2>/dev/null
+  grep '^! angle(0,0) is taken as zero.' $$.errs >$$.angle 2>/dev/null
+  cat $$.badpos $$.strange $$.angle | sort > $$.errs_accept
+  if cmp $$.errs $$.errs_accept >/dev/null 2>&1; then
+    test -s $$.strange >/dev/null 2>&1 \
+      && echo "$progname: warning: \`$cmd' caused strange path errors." >&2
+    test -s $$.badpos >/dev/null 2>&1 \
+      && echo "$progname: warning: \`$cmd' caused bad pos errors." >&2
+    test -s $$.angle >/dev/null 2>&1 \
+      && echo "$progname: warning: \`$cmd' caused angle(0,0) errors." >&2
   else
     echo "$progname: \`$cmd' failed." >&2
     test -s $NAME.log && mv -f $NAME.log "$KPSE_DOT"
